### ISSUE TITLE
Searchyll doesn't connect to local Elasticsearch url

### ISSUE THREAD

**Issue by ravi9884** [omc/searchyll#27]
I am newbie with gems. Pardon if this is pretty basic. I am using this blog https://blog.omc.io/elasticsearch-for-jekyll-part-2-5ff5e52912bf to setup searchyll. I get the below error when I try to build with Searchyll Jekyll.

Thanks in advance. This plugin is awesome!!

```
jekyll build
            Source: /<localpath>/advisor
       Destination: /<localpath>/advisor/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
jekyll 3.6.2 | Error:  Failed to open TCP connection to :80 (Connection refused - connect(2) for nil port 80)
```

The error disappears when I comment out the Searchyll plugin

Env
jekyll 3.6.2 
MacBook Pro running High Sierra

Contents of _config.yml
```
title: Your awesome title
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - searchyll

elasticsearch:
    url: http:/127.0.0.1:9200
    index_name: jekyll-shakespeare
```

contents of Gemfile
```
source "https://rubygems.org"

gem "jekyll", "~> 3.6.2"

gem "minima", "~> 2.0"


group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.6"
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

source 'https://rubygems.org'
gem 'searchyll'
gem 'jekyll-compose', group: [:jekyll_plugins]
```

**Comment by robsears** [comment]
Maybe a silly question, but should this:

```yml
elasticsearch:
    url: http:/127.0.0.1:9200
    index_name: jekyll-shakespeare
```

actually be this:

```yml
elasticsearch:
    url: http://127.0.0.1:9200
    index_name: jekyll-shakespeare
```

If that's not it, have you tried `localhost:9200`? I'm not sure this is a problem with Searchyll, because it's configured to use port 9200. I'm not sure where the port 80 stuff is coming from.
