### ISSUE TITLE
Provide a means to separate collections

### ISSUE THREAD

**Issue by drusellers** [omc/searchyll#32]
I want to have a means to index all of the content in a jekyll site but then filter on collection when searching.

**Comment by alranel** [comment]
@drusellers you can assign a default value to each collection in Jekyll config:

```yaml
   platforms:
     output: true
     permalink: /:path/

defaults:
  -
    scope:
      path: ""
      type: "platforms"
    values:
      toc: true
      layout: platform
      mykey: platform
```

Then you can filter by `mykey` when searching in Elasticsearch.
